import Head from "next/head";
// import ReserveForm from "../components/reservation/ReserveForm";
// import CardDisplay from "../components/layout/CardDisplay";
// import { getTimeSlot } from "../components/variables/timeslot";
// import AllHeader from "../components/layout/AllHeader";

// //SSG
// export async function getStaticProps() {
//   const { timeOptionsFixed, timeOptions } = getTimeSlot();

//   return {
//     props: {
//       timeOptionsFixed,
//       timeOptions,
//     },
//   };
// }

const title = "Create your reservation";

export default function Home() {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <AllHeader title={title}>
        {/* <CardDisplay>
          <ReserveForm
            timeOptionsFixed={timeOptionsFixed}
            timeOptions={timeOptions}
          />
        </CardDisplay> */}
      {/* </AllHeader> */}
    </div>
  );
}
