import Head from "next/head";
import React from "react";
import ReserveForm from "./presenter";
import CardDisplay from "../../uiParts/CardDisplay";
import AllHeader from "../../uiParts/AllHeader";
import { GetStaticProps } from "next/types";

interface timeSlotTypes {
  timeOptionsFixed: string[];
  timeOptions: string[];
}

//SSG

const title = "Create your reservation";

export default function Home({ timeOptionsFixed, timeOptions }: timeSlotTypes) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AllHeader title={title}>
        <CardDisplay>
          <ReserveForm />
        </CardDisplay>
      </AllHeader>
    </div>
  );
}
